createkn01 knapsack01.txt:
	javac createkn01.java 
	java createkn01 knapsack01.txt

bruteforce knapsack01.txt:
	javac bruteforce.java
	java bruteforce knapsack01.txt

dynpro knapsack01.txt:
	javac dynpro.java
	java dynpro knapsack01.txt

igreedy knapsack01.txt:
	javac igreedy.java
	java igreedy knapsack01.txt
